config/routes.rb
Rails.application.routes.draw do

  get 'what_is_the_time_now'=>'static#server_time'
  get 'show_price'=>'quotations#show_price'
  get 'show_total_cost/:id' => 'quotations#show_total_cost'
  get 'calculator'=>'quotations#calculator'
  get 'fits/show'

  resources :quotations
  resources :brands
  resources :shirt_types
  resources :customers
  resources :print_methods
  resources :additional_infos
  resources :relabel

  root 'home#index'

  devise_for :apparel_consultants, :skip => [:registrations]
  as :apparel_consultant do
    get 'apparel_consultants/edit' => 'devise/registrations#edit', :as => 'edit_apparel_consultant_registration'
    put 'apparel_consultants' => 'devise/registrations#update', :as => 'apparel_consultant_registration'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  # def generateform
  #   require "prawn"
  #
  #   Prawn::Document.generate("hello.pdf") do
  #     # image "/app/assets/images/saltylogoblack.png"
  #     image Rails.root.join('app','assets','images','saltylogoblack.png').to_s, scale: 0.25
  #     move_down 20
  #     font "Arial",:style => :bold_underline
  #     text "Hello World!"
  #   end
  #   redirect_to root_path
  # end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!-- <h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p> -->
<div class="home">
<% if apparel_consultant_signed_in? %>
  <h1> Hi <%= current_apparel_consultant.name %></h1>
  <% if Time.now.in_time_zone>Time.new.noon().in_time_zone%>
    <% if Time.now.in_time_zone>(Time.new.noon().in_time_zone+120.minutes) %>
    <h2>Good Evening</h2>
    <% else %>
    <h2>Good Afternoon</h2>
    <% end %>
  <% else%>
    <h2>Good Morning</h2>
  <% end %>
  <p >  Welcome to Salty Quotation, to create quotation simply press <strong>New</strong> on the navigation bar.<br/>
    To browse through quotation list simply click on the <strong>Quotation</strong> on the navigation bar.<br/>
    To use the calculator, simply click on the <strong>Calculator</strong> on the navigation bar.
  </p>

  <!-- <%= link_to "Sign out", destroy_apparel_consultant_session_url, method: :delete %> -->
  <%= link_to "Click me to add quotation", quotations_url,class:"btn btn-default" %>
<% else %>
  <h1>SaltyQuotation</h1>
  <p>All the Apparel Consultant are require to login.<br/>
    If you didn't have an account yet, kindly click on <strong>Sign Up</strong> button to register.<br/>
  If you already have an account, kindly click on the <strong>Sign In</strong> button to login.<br/>
Thank you.</p>
  <%= link_to "Sign in", new_apparel_consultant_session_url,class:"btn btn-default" %><br/>

<% end %>
</div>