config/routes.rb
Rails.application.routes.draw do

  get 'what_is_the_time_now'=>'static#server_time'
  get 'show_price'=>'quotations#show_price'
  get 'show_total_cost/:id' => 'quotations#show_total_cost'
  get 'calculator'=>'quotations#calculator'
  get 'fits/show'

  resources :quotations
  resources :brands
  resources :shirt_types
  resources :customers
  resources :print_methods
  resources :additional_infos
  resources :relabel

  root 'home#index'

  devise_for :apparel_consultants, :skip => [:registrations]
  as :apparel_consultant do
    get 'apparel_consultants/edit' => 'devise/registrations#edit', :as => 'edit_apparel_consultant_registration'
    put 'apparel_consultants' => 'devise/registrations#update', :as => 'apparel_consultant_registration'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
  validates :customer, presence: true
  validates :quantity, presence: true
  validates :shirt_type,presence: true
  validates :fit,presence: true
  validates :front_block_no,presence: true,numericality:{less_than:11}
  validates :back_block_no,presence: true,numericality:{less_than:11}
  validates :left_block_no,presence: true,numericality:{less_than:11}
  validates :right_block_no,presence: true,numericality:{less_than:11}
  validates :special_print,presence: true,numericality:{less_than:3,only_integer:true}
  validates :sew_tag_charge_cents,numericality:{only_integer:true}
  register_currency :sgd
  monetize :budget_cents
  monetize :rush_fee_cents
  monetize :delivery_fee_cents
  monetize :price_cents
  monetize :cost_cents
  monetize :min_rrp_cents
  monetize :max_rrp_cents
  monetize :actual_price_cents
  monetize :total_cost_cents
  monetize :sew_tag_charge_cents
  monetize :woven_tag_charge_cents
  monetize :relabel_charge_cents

  belongs_to :customer
  # belongs_to :design
  belongs_to :shirt_type
  belongs_to :brand
  belongs_to :fit
  # belongs_to :printing_detail, foreign_key: "printing_id"
  # has_one :front_print, class_name: "Print", foreign_key: "front_print_id"
  # has_one :back_print, class_name: "Print", foreign_key: "back_print_id"
  # has_one :left_print, class_name: "Print", foreign_key: "left_print_id"
  # has_one :right_print, class_name: "Print", foreign_key: "right_print_id"

  belongs_to :front_print_method, foreign_key: "front_print_method_id",class_name:"PrintMethod"
  belongs_to :front_block_size,foreign_key: "front_block_size_id",class_name:"BlockSize"
  # belongs_to :block_no,foreign_key: "front_block_no_id"

  belongs_to :back_print_method, foreign_key: "back_print_method_id",class_name:"PrintMethod"
  belongs_to :back_block_size,foreign_key: "back_block_size_id",class_name:"BlockSize"
  # belongs_to :block_no,foreign_key: "back_block_no_id"

  belongs_to :left_print_method, foreign_key: "left_print_method_id",class_name:"PrintMethod"
  # belongs_to :block_no,foreign_key: "left_block_no_id"

  belongs_to :right_print_method, foreign_key: "right_print_method_id",class_name:"PrintMethod"
  # belongs_to :block_no,foreign_key: "right_block_no_id"

  belongs_to :apparel_consultant, foreign_key: "ac_id"

  belongs_to :approver, foreign_key: "approval_id",class_name:"ApparelConsultant"

  # belongs_to :costing
  # belongs_to :negotiation
  has_many :additional_infos

  accepts_nested_attributes_for :brand
  accepts_nested_attributes_for :shirt_type
  accepts_nested_attributes_for :fit
  accepts_nested_attributes_for :additional_infos
  accepts_nested_attributes_for :customer
  def showprice(shirtid,fitid,methodid,sizeid,quantity,noblock)
    @shirtprice = ShirtType.all.find(shirtid).shirt_type_fit_relations.where("fit_id = ? AND ?<= end_quantity AND ?>=start_quantity",fitid,quantity,quantity).first.price
    # @printprice = PrintMethod.all.find(methodid).print_method_block_size_relations.where("block_size_id = ? AND ? <= end_quantity AND ? >= start_quantity",sizeid,quantity,quantity).first.price
    # @printblockcharge = PrintMethod.all.find(methodid).print_method_block_size_relations.where("block_size_id = ? AND ? <= end_quantity AND ? >= start_quantity",sizeid,quantity,quantity).first.block_charge_price
    @printprice = PrintMethod.all.showprice(methodid,sizeid,quantity)
    @printblockcharge = PrintMethod.all.showblockcharge(methodid,sizeid,quantity)
    @price = @shirtprice+@printprice+(@printblockcharge*noblock.to_i)
  end

  def showcost(shirtid,fitid,methodid,sizeid,quantity,noblock)
    @shirtprice = ShirtType.all.find(shirtid).shirt_type_fit_relations.where("fit_id = ? AND ?<= end_quantity AND ?>=start_quantity",fitid,quantity,quantity).first.price
    @printprice = PrintMethod.all.find(methodid).print_method_block_size_relations.where("block_size_id = ? AND ? <= end_quantity AND ? >= start_quantity",sizeid,quantity,quantity).first.price
    @printblockcharge = PrintMethod.all.find(methodid).print_method_block_size_relations.where("block_size_id = ? AND ? <= end_quantity AND ? >= start_quantity",sizeid,quantity,quantity).first.block_charge_price
    @cost = (@shirtprice+@printprice+(@printblockcharge*noblock.to_i))*quantity.to_i
  end

  def update_total_cost(id)
      quotation = Quotation.find(id)
      actual_price = quotation.actual_price_cents
      quantity = quotation.quantity
      rush_order_fee = quotation.rush_fee_cents
      delivery_fee = quotation.delivery_fee_cents
      additional_price = AdditionalInfo.new.additional_info_price(id)

      # if(!quotation.additional_infos.blank?)
      #   quotation.additional_infos do |additional_info|
      #     if(!additional_info.approval_id.blank?)
      #       additional_price = additional_price + additional_info.price_cents
      #     end
      #   end
      # end
      total_cost = actual_price*quantity+additional_price+rush_order_fee+delivery_fee
      quotation.update(total_cost_cents:total_cost)
  end

end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_filter :authenticate_apparel_consultant!
  def index
    # @quotations = Quotation.all
    @quotations = Quotation.order('id DESC').page(params[:page]).per_page(10)
  end

  def new
    @quotation = Quotation.new
    @quotation.customer = Customer.new
    # @brand = Brand.all
    # @quotation.brand = Brand.new
    # @quotation.fit = Fit.new
    # @quotation.shirt_type = ShirtType.new

  end

  # def update_fits
  #   brand = Brand.find(params[:brand_id])
  #   fit = brand.fit
  #
  #   render :update do |page|
  #     page.replace_html 'quotation_fit_id', :partial => 'quotation_fit_id', :object => songs
  #   end
  # end
  def show
    @quotation = Quotation.find(params[:id])
  end

  def calculator
    @quotation= Quotation.new
  end

  def show_price
    # @show_price = Quotation.new.showprice(params[:shirtid],params[:fitid],params[:methodid],params[:sizeid],params[:quantity],params[:noblock])
    shirt_price = 0
    front_price = 0
    back_price = 0
    right_price = 0
    left_price = 0

    if(!(params[:shirt_type_id].blank?||params[:fit_id].blank?||params[:quantity].blank?))
      shirt_price = ShirtType.all.showprice(params[:shirt_type_id],params[:fit_id],params[:quantity])
    end

    if(!(params[:front_print_method_id].blank?||params[:front_block_size_id].blank?||params[:quantity].blank?))
      tempprice = PrintMethod.all.showprice(params[:front_print_method_id],params[:front_block_size_id],params[:quantity])
      tempblockcharge = PrintMethod.all.showblockcharge(params[:front_print_method_id],params[:front_block_size_id],params[:quantity])
      front_price = tempprice + tempblockcharge*params[:front_block_no].to_i
    end

    if(!(params[:back_print_method_id].blank?||params[:back_block_size_id].blank?||params[:quantity].blank?))
      tempprice = PrintMethod.all.showprice(params[:back_print_method_id],params[:back_block_size_id],params[:quantity])
      tempblockcharge = PrintMethod.all.showblockcharge(params[:back_print_method_id],params[:back_block_size_id],params[:quantity])
      back_price = tempprice + tempblockcharge*params[:back_block_no].to_i
    end

    if(!(params[:left_print_method_id].blank?||params[:quantity].blank?))
      tempprice = PrintMethod.all.showsleeveprice(params[:left_print_method_id],params[:quantity])
      tempblockcharge = PrintMethod.all.showsleeveblockcharge(params[:left_print_method_id],params[:quantity])
      left_price = tempprice + tempblockcharge*params[:left_block_no].to_i
    end

    if(!(params[:right_print_method_id].blank?||params[:quantity].blank?))
      tempprice = PrintMethod.all.showsleeveprice(params[:right_print_method_id],params[:quantity])
      tempblockcharge = PrintMethod.all.showsleeveblockcharge(params[:right_print_method_id],params[:quantity])
      right_price = tempprice + tempblockcharge*params[:right_block_no].to_i
    end

    special_print = Money.new(params[:special_print].to_i*100,"SGD")
    @show_price = shirt_price+front_price+back_price+left_price+right_price+special_print
    @show_cost = (shirt_price+front_price+back_price+left_price+right_price+special_print)*params[:quantity].to_i
    @show_min_rrp = @show_price-(@show_price/100)
    @show_max_rrp = @show_price+(@show_price/100)
  end

  def create
    @quotation = current_apparel_consultant.quotations.new(quotation_params)
    # respond_to do |format|
    #   format.html
    #   format.js{}
    #   format.json {
    #     render json: {quotation: @quotation}
    #   }
    # end
    if @quotation.save
      redirect_to @quotation
    else
      render 'new'
    # render :json => @quotation
    end
  end

  def edit
    @quotation = Quotation.find(params[:id])
  end

  def update
    @quotation = Quotation.find(params[:id])
    if @quotation.update(quotation_params)
      # redirect_to @quotation
      redirect_to @quotation
    else
      render 'edit'
    end
  end

  def destroy
    @quotation = Quotation.find(params[:id])
    @quotation.destroy

    redirect_to quotations_path
  end

  private
   def quotation_params

    #  ActionController::Parameters.permit_all_parameters = true
     params.require(:quotation).permit!
   end
end

app/helpers/quotation_helper.rb
module QuotationHelper
end

app/views/quotations/edit.html.erb
<%= render 'form' %>

app/views/quotations/index.html.erb
<h1>Quotation</h1>
<!-- <p>Find me in app/views/quotation/index.html.erb</p> -->
<p> Below is the quotation table</p>
<table class="table table-hover">
  <tr>
    <th>QuotationID</th>
    <th>Client's Name</th>
    <th>Client Contact</th>
    <th>Quantity</th>
    <th>Total Cost</th>
    <th>Delivery Status</th>
  </tr>
<% @quotations.each do |quotation| %>
  <tr class="selectable-row" data-href="<%=quotation_path(quotation) %>">
    <td><%= quotation.id %></td>
    <td><%= quotation.customer.full_name unless quotation.customer.nil? %></td>
    <td><%= quotation.customer.contact unless quotation.customer.nil? %></td>
    <td><%= quotation.quantity %></td>
    <td><%= quotation.total_cost %></td>
    <td><%= quotation.delivered == 1 ? "Y" : "N" %></td>
    <!-- <td><%= link_to 'Show',quotation_path(quotation) %> </td> -->
    <% if current_apparel_consultant.approve_right==1 %>
    <td class="not-show"><%= link_to edit_quotation_path(quotation) do %><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><% end %></td>
    <td class="not-show"><%= link_to quotation_path(quotation),method: :delete, data: {confirm: 'Are you sure you want to delete?'} do %><span class="glyphicon glyphicon-trash" aria-hidden="true"></span><% end %></td>
    <% elsif current_apparel_consultant.id==quotation.ac_id%>
    <td class="not-show"><%= link_to edit_quotation_path(quotation) do %><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><% end %></td>
    <% end %>
  </tr>
<% end %>
</table>
<%= will_paginate @quotations, :style => 'color:black' %>
<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
<%= link_to "Create Quotation", new_quotation_url %>

app/views/quotations/new.html.erb
<%  if !apparel_consultant_signed_in? %>
    <% redirect_to new_apparel_consultant_session_url %>
  <% end %>
<% if @quotation.errors.any? %>
  <div class="alert alert-danger">
    <h2>
      <!--%= @article.errors.count %> error prohibited this article from being saved:-->

      <!-- This is added a 's' on 'error' if there is more than one error -->
      <%= pluralize(@quotation.errors.count,"error") %> prohibited this quotations from being saved:
    </h2>
    <ul>
      <% @quotation.errors.full_messages.each do |msg| %>
        <li><%=msg%></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= nested_form_for @quotation,html:{class:"form-horizontal"} do |f| %>

<fieldset>
  <legend>Client Info</legend>
  <%= f.fields_for :customer,@quotation.customer do |customer_fields| %>

    <div class="form-group">
      <%= customer_fields.label :full_name,"Client's Name:",class:"col-sm-2 control-label" %>
      <!-- <%= customer_fields.text_field :full_name,data: {clsource: customers_path} %><br/> -->
      <div class="col-sm-10">
        <%= customer_fields.text_field :full_name,class:"form-control"%><br/>
      </div>
    </div>
    <div class="form-group">
      <%= customer_fields.label :contact,"Client's Contact Number:",class:"col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= customer_fields.text_field :contact,class:"form-control"%><br/>
      </div>
    </div>
    <div class="form-group">
      <%= customer_fields.label :address_line1,"Client's Address Line 1:",class:"col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= customer_fields.text_field :address_line1,class:"form-control" %><br/>
      </div>
    </div>
    <div class="form-group">
    <%= customer_fields.label :address_line2,"Client's Address Line 2:",class:"col-sm-2 control-label" %>
      <div class = "col-sm-10">
        <%= customer_fields.text_field :address_line2,class:"form-control" %><br/>
      </div>
    </div>
    <div class="form-group">
    <%= customer_fields.label :address_line3,"Client's Address Line 3:",class:"col-sm-2 control-label" %>
      <div class = "col-sm-10">
        <%= customer_fields.text_field :address_line3,class:"form-control" %><br/>
      </div>
    </div>
    <div class="form-group">
    <%= customer_fields.label :city,"Client's City:",class:"col-sm-2 control-label" %>
      <div class = "col-sm-10">
        <%= customer_fields.text_field :city,class:"form-control" %><br/>
      </div>
    </div>
    <div class="form-group">
    <%= customer_fields.label :postal,"Client's Postal:",class:"col-sm-2 control-label" %>
      <div class = "col-sm-10">
        <%= customer_fields.text_field :postal,class:"form-control" %><br/>
      </div>
    </div>
    <div class="form-group">
    <%= customer_fields.label :state,"Client's State:",class:"col-sm-2 control-label" %>
      <div class = "col-sm-10">
        <%= customer_fields.text_field :state,class:"form-control" %><br/>
      </div>
    </div>
    <div class="form-group">
    <%= customer_fields.label :country,"Client's Country:",class:"col-sm-2 control-label" %>
      <div class = "col-sm-10">
    <!-- <%= customer_fields.text_field :country %> -->
    <%= customer_fields.country_select("country",{},{class:"form-control"}) %><br/>
      </div>
    </div>
  <% end %>
</fieldset>
<fieldset>
  <legend>Basic Info</legend>
  <div class="form-group">
    <%= f.label :design_file_name,"Design File Name:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :design_file_name,class:"form-control" %><br/>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :budget_cents,"Client's Budget:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :budget_cents,class:"form-control" %><br/>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :deadline,"Client's Deadline:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :deadline,{},{class:"form-control-static"} %><br/>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rush_fee_cents,"Rush Order Fee:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :rush_fee_cents,class:"form-control" %><br/>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :delivered, "Delivery:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:delivered,[["No",0],["Yes",1]],{},{class:"form-control"}) %><br/>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :delivery_fee_cents, "Delivery Fee:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :delivery_fee_cents,class:"form-control" %><br/>
    </div>
  </div>
</fieldset>

<fieldset>
  <legend>Shirt</legend>
  <div class="form-group">
    <%= f.label :quantity, "Quantity:",class:"col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :quantity,class:"form-control" %><br/>
  </div>
  </div>
  <div class="form-group">
    <%= f.label :brand_id,"Brand:",class:"col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.collection_select(:brand_id,Brand.order(:name),:id,:name,{prompt:"Select A Brand"},{class:"form-control"}) %> <br/>
    </div>
  </div>
  <div class="form-group">
    <%=f.label :shirt_type_id,"Shirt Type:",class:"col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.collection_select(:shirt_type_id,ShirtType.order(:name),:id,:name,{:prompt => "Select A Type"},{class:"form-control"}) %><br/>
    </div>
  </div>
  <div class="form-group">
    <%=f.label :fit_id,"Fit:",class:"col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.collection_select(:fit_id,Fit.order(:name),:id,:name,{:prompt => "Select A Fit"},{class:"form-control"}) %><br/>
    </div>
  </div>
</fieldset>
<fieldset>
  <legend>Printing Details</legend>
  <fieldset id="second-level-fieldset">
  <legend>Front Print </legend>
  <div class="form-group">
    <%= f.label :front_print_method_id,"Print Method:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select(:front_print_method_id,PrintMethod.order(:name),:id,:name,{:prompt => "Select A Print Method"},{class:"form-control"}) %><br/>
    </div>
    </div>
    <div class="form-group">
    <%= f.label :front_block_size_id,"Block Size:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select(:front_block_size_id,BlockSize.order(:name),:id,:name,{:prompt => "Select A Block Size"},{class:"form-control"}) %><br/>
    </div>
    </div>
    <div class="form-group">
    <%= f.label :front_block_no,"No. of Blocks:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :front_block_no,class:"form-control" %><br/>
    </div>
    </div>
  </fieldset>
  <fieldset id="second-level-fieldset">
  <legend>Back Print  </legend>
  <div class="form-group">
    <%= f.label :back_print_method_id,"Print Method:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select(:back_print_method_id,PrintMethod.order(:name),:id,:name,{:prompt => "Select A Print Method"},{class:"form-control"}) %><br/>
    </div>
    </div>
    <div class="form-group">
    <%= f.label :back_block_size_id,"Block Size:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select(:back_block_size_id,BlockSize.order(:name),:id,:name,{:prompt => "Select A Block Size"},{class:"form-control"}) %><br/>
    </div>
    </div>
    <div class="form-group">
    <%= f.label :back_block_no,"No. of Blocks:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :back_block_no,class:"form-control" %><br/>
    </div>
    </div>
  </fieldset>
  <fieldset id="second-level-fieldset">
  <legend>Left Sleeve </legend>
  <div class="form-group">
    <%= f.label :left_print_method_id,"Print Method:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select(:left_print_method_id,PrintMethod.order(:name),:id,:name,{:prompt => "Select A Print Method"},{class:"form-control"}) %><br/>
    </div>
    </div>
    <div class="form-group">
    <%= f.label :left_block_no,"No. of Blocks:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :left_block_no,class:"form-control" %><br/>
    </div>
    </div>
  </fieldset>
  <fieldset id="second-level-fieldset">
  <legend>Right Sleeve </legend>
  <div class="form-group">
    <%= f.label :right_print_method_id,"Print Method:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select(:right_print_method_id,PrintMethod.order(:name),:id,:name,{:prompt => "Select A Print Method"},{class:"form-control"}) %><br/>
    </div>
    </div>
    <div class="form-group">
    <%= f.label :right_block_no,"No. of Blocks:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :right_block_no,class:"form-control" %><br/>
    </div>
    </div>
  </fieldset>
    <div class="form-group">
    <%= f.label :special_print,"Special Print:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :special_print,class:"form-control" %><br/>
    </div>
    </div>
</fieldset>
 <%= f.button "Calculate" , {type: "button",id:"calculate",class:"btn btn-info"} %>
<fieldset>
  <legend>Costing</legend>
    <div class="form-group">
    <%= f.label :price_cents,"Price:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :price_cents,class:"form-control" %><br/>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cost_cents, "Cost:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cost_cents,class:"form-control" %><br/>
    </div>
  </div>
</fieldset>
<fieldset>
  <legend>Negotiations</legend>
    <div class="form-group">
    <%= f.label :min_rrp_cents, "Min RRP:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :min_rrp_cents,class:"form-control" %><br/>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :max_rrp_cents, "Max RRP:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :max_rrp_cents,class:"form-control" %><br/>
    </div>
  </div>
</fieldset>
<fieldset>
  <legend>Final Costing</legend>
    <div class="form-group">
    <%= f.label :actual_price_cents, "Final Price:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :actual_price_cents,{value: 0,class:"form-control"} %><br/>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :total_cost_cents, "Total Cost:",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :total_cost_cents,{value: 0,class:"form-control"} %><br/>
    </div>
  </div>
</fieldset>
<fieldset>
  <legend>Additional Info</legend>
    <%= f.fields_for :additional_infos do |additional_info_form| %>
      <div class="form-group">
        <%= additional_info_form.label :description,"Description:",class:"col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= additional_info_form.text_area :description,class:"form-control" %><br/>
        </div>
      </div>
      <div class="form-group">
        <%= additional_info_form.label :price_cents,"Price:",class:"col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= additional_info_form.text_field :price_cents,class:"form-control" %><br/>
        </div>
      </div>
      <%= additional_info_form.link_to_remove "Remove this task" %>
    <% end %>
</fieldset>
    <p><%= f.link_to_add "Add Additional Info", :additional_infos %></p>

  <!-- <button > Add Additional Info </button> -->
  <button type="submit" class="btn btn-primary" >Submit </button>
  <!-- <%= button_to "Submit",{type:"submit",class:"btn btn-primary"} %> -->
<% end %>

<div id="test" > </div>

app/views/quotations/show_price.html.erb
<%= @show_price %>
<%= @show_cost %>